version: '3.3'

services:
  basic_ci_cd:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: basic_ci_cd
    ports:
      - 5001:80
    environment:
      - ASPNETCORE_URLS=http://+:80